### ISSUE TITLE
Missing / exists filter doesn't seem to be working on native driver

### ISSUE THREAD

**Issue by ronaldsuwandi** [clojurewerkz/elastisch#179] opened 2015-10-11 23:56 UTC
missing / exists filter doesn't seem to work with elastisch. I have the following records
```
{:name "a" :email "a@a.com"}
{:name "b" :email nil}
{:name "c" :email nil}
```

and querying it directly from elastic search works fine `GET /uni_test/users/_search` returns all 3 records while 
```
GET /uni_test/users/_search
{
    "query": {
        "filtered": {
            "query": {
                "match_all": {}
            },
            "filter":{
                "missing": {
                    "field": "email"
                }
            }
        }        
    }
}
```
returns 2 records as expected, but when I do it in elastisch I keep getting all 3 records
```
(doc/search *es* test-index (name :users)
                          {:query {:filtered {:filter {:missing {:field :email}}
                                              :query {:match_all {}}}}})
```
I’ve tried with both `:filter` and `:query` as well as `:filtered` query, also tried using elastisch 2.1.0, 2.2.0-beta4 and even upgraded elasticsearch client to 1.7.2 without any luck

**Comment by ronaldsuwandi** [comment] 2015-10-12 02:59
Forgot to mention it works fine on *rest* driver but not on native driver

**Comment by michaelklishin** [comment] 2015-10-12 09:23
Thanks. This is a duplicate of #145. May I ask you to post the above examples there?

**Closed by michaelklishin** 2015-10-12 09:23 UTC

**Comment by ronaldsuwandi** [comment] 2015-10-12 09:30
Thanks @michaelklishin will do
